# https://github.com/openai/codex/blob/main/docs/config.md
# https://developers.openai.com/codex/config-sample

profile = "claude"

model_reasoning_effort = "high"
model_reasoning_summary = "detailed"

web_search = "live"
approval_policy = "on-request"
sandbox_mode = "workspace-write"

show_raw_agent_reasoning = true

[tui]
notifications = true

[profiles.my-gpt-5]
model = "gpt-5.1-chat"
model_provider = "azure-chat"

[profiles.claude]
model = "anthropic/claude-opus-4.6"
model_provider = "litellm"

[model_providers.azure-chat]
name = "azure-chat"
base_url = "https://safuapi.prod.secfdg.net/openai/deployments/gpt-5.1-chat"
query_params = { api-version = "2025-04-01-preview" }
env_key = "OPENAI_API_KEY"

[model_providers.litellm]
name = "litellm"
base_url = "https://litellm.safuapi.prod.secfdg.net"
experimental_bearer_token = "sk-innP6c3duu05DtIVmglJyw"

[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]
