[shell]
change-ps1 = true

[pypi-config]
index-url = "https://mirrors.sustech.edu.cn/pypi/web/simple"

[mirrors]
"https://conda.anaconda.org/conda-forge" = ["https://mirrors.sustech.edu.cn/anaconda/cloud/conda-forge"]
